title: My test site
author: author
email: admin@github.com
description: > # this means to ignore newlines until "baseurl:"
 This is my test site in the github jekyll tutorial
 
# social links
twitter_username: @mattlinzer
github_username:  mattlinzer

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
